<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    protected $fillable = ['title','content','image','user_id','tag_id'];

    public function tag()
    {
        return self::belongsTo(Tag::class,'tag_id','tag_id');
    }

    public function user()
    {
        return self::belongsTo(User::class,'id','user_id');
    }
    public function create(array $attributes = [])
    {
        if (!isset($attributes['user_id']))
            $attributes['user_id']='1';
        return parent::create($attributes); // TODO: Change the autogenerated stub
    }

}
